imports:
  - { resource: '../Modules/*/config/services.yaml' }

services:
  App\Controller\:
    resource: '../src/Controller'
    tags: ['controller.service_arguments']

  App\Controller\DemoController:
    autowire: true
    autoconfigure: true
    public: true
  # сервисы вручную
  App\Service\GreetingService:
    public: true
