imports:
  - { resource: '../Modules/module_one/config/module_one_services.yaml' }
  - { resource: '../Modules/module_two/config/module_two_services.yaml' }

services:
  App\Controller\:
    resource: '../src/Controller'
    tags: ['controller.service_arguments']

  App\Controller\DemoController:
    autowire: true
    autoconfigure: true
    public: true
  # сервисы вручную
  App\Service\GreetingService:
    public: true
